### ISSUE TITLE
#008:Section-7(FIGMA)-(Customer Reviews)

### ISSUE THREAD

**Issue by Mayank1st** [Mayank1st/Beas-Boolean-009#10]
@rohit7979 '
Introduction:
Design **Customer Reviews** Section.

Steps to Reproduce:

- [x] Use grid to draw table
- [x] Add responsiveness
- [x] Add images.
- [x] Use Inter Font Family.

Expected Behavior:
The  **Customer Reviews** should align to center when zoom out the webpage.

Possible Solution:
Use Figma Tool and Sass framework.

Environment Details:

Browser: Chrome 14.0.3
Operating System: Windows 11.2.3

**Comment by rohit7979** [comment]
Overview:
This pull request addresses an issue where the Use grid to draw table is introduced. The fix ensures that the grid aligns correctly across all devices.

Changes:
- Use grid to draw table completed.
- Use Inter Font Family completed.

Request for Review:
Please review the changes and provide any feedback or suggestions for improvement. Thank you!
References:
Related issue: #10

![Screenshot 2024-05-09 004718](https://github.com/Mayank1st/Beas-Boolean-009/assets/154664605/d3bae7d2-37d6-4dff-aa46-71825294e00f)

**Comment by Mayank1st** [comment]
Title: Fix issue with Font-Family, use **Inter** font family.

Overview:
This pull request addresses an issue where the font-family  is different from the actual one. on smaller screens, causing a poor user experience. 

Changes:

- [x] Use grid to draw table completed.
- [x] Use Inter Font Family.

References:
Related issue: #10

**Comment by rohit7979** [comment]
Overview:
This pull request addresses an issue where the Add responsiveness and Add images are introduced. The fix ensures that the responsiveness is correct across all devices.

Changes:

Add responsiveness completed.
 Add images. completed.
Request for Review:
Please review the changes and provide any feedback or suggestions for improvement. Thank you!
References:
Related issue: #10
![Screenshot 2024-05-10 022705](https://github.com/Mayank1st/Beas-Boolean-009/assets/154664605/68cf5eb5-0aa5-4abb-9f08-ac716cee7f00)

**Comment by rohit7979** [comment]
Use Inter Font Family completed
and form section added as well;
![Screenshot 2024-05-12 010515](https://github.com/Mayank1st/Beas-Boolean-009/assets/154664605/3aeba738-4daf-4445-b751-3fd8fae24fa7)

**Comment by Mayank1st** [comment]
Okay Sorted.
