### ISSUE TITLE
#003:Section-3(Easily explore )

### ISSUE THREAD

**Issue by Mayank1st** [Mayank1st/Beas-Boolean-009#4]
@vivekkmrpaswan 
**Introduction**:
Design **Easily Explore** Section.

**Steps to Reproduce**:

- [x] Open the website on Chrome browser.
- [x] Navigate to the Easily Explore Section.
- [x] Add Responsiveness and background texture.
- [x] Add icons.

**Expected Behavior**:
The **Easily Explore** should align to center when zoom out the webpage.

**Possible Solution**:
Use Bootstrap framework, canva and fontawesome.

**Environment Details**:
- Browser: Chrome 14.0.3
- Operating System: Windows 11.2.3

**Comment by vivekkmrpaswan** [comment]
Overview:

This pull request addresses an issue where the Easily_explore was misaligned on smaller screens, causing a poor user experience. The fix ensures that the button aligns correctly across all devices.

Changes:
1. Open the website on Chrome browser completed.
2. Navigate to the Easily Explore Section completed.
3. Icons added

Request for Review:
Please review the changes and provide any feedback or suggestions for improvement. Thank you!
References:
Related issue: Easily_explore section
![cw-project-sec3-img](https://github.com/Mayank1st/Beas-Boolean-009/assets/167101531/3de4066f-45b7-414b-a940-835a9d92aabd)

**Comment by Mayank1st** [comment]
Title: Add responsiveness **Section-3**

Overview:
This pull request addresses an issue where the responsiveness was misaligned on smaller screens, causing a poor user experience. The fix ensures that the button aligns correctly across all devices.

Changes:

- [x] Open the website on Chrome browser.
- [x] Navigate to the Easily Explore Section.
- [x]  Add Responsiveness and background texture.
- [x] Add icons.

References:
Related issue: #4

**Comment by vivekkmrpaswan** [comment]
Overview:

This pull request addresses an issue where the Easily_explore was misaligned on smaller screens, c
ausing a poor user experience. The fix ensures that the button aligns correctly across all devices.

Changes:
1. Open the website on Chrome browser completed.
2. Navigate to the Easily Explore responsiveness completed.

Request for Review:
Please review the changes and provide any feedback or suggestions for improvement. Thank you!
References:
Related issue: Easily_explore section

<img width="958" alt="image" src="https://github.com/Mayank1st/Beas-Boolean-009/assets/167101531/9b33aa38-e60a-4f28-b654-a0a940e1714b">
