### ISSUE TITLE
#004:Section-4(You share)

### ISSUE THREAD

**Issue by Mayank1st** [Mayank1st/Beas-Boolean-009#5]
@vivekkmrpaswan 
**Introduction**:
Design **You share**  Section.

**Steps to Reproduce**:

- [x] Open the website on Chrome browser.
- [x] Navigate to the **You Share** Section.
- [x] Add Responsiveness.
- [x] Add hover effect to all buttons.
- [x] Use icons for tick mark.

**Expected Behavior**:
The navbar should align to center when zoom out the webpage.

**Possible Solution**:
Use Bootstrap framework and fontawesome.

**Environment Details**:
- Browser: Chrome 14.0.3
- Operating System: Windows 11.2.3

**Comment by vivekkmrpaswan** [comment]
Title: Section You Share added

Overview:
This pull request addresses an issue where the You Share was misaligned on smaller screens, causing a poor user experience. The fix ensures that the section correctly across all devices.
Changes:
- Updated CSS styles to adjust the positioning of the You Share section

Request for Review:
Please review the changes and provide any feedback or suggestions for improvement. Thank you!

References:
Related issue: #5 

<img width="911" alt="image" src="https://github.com/Mayank1st/Beas-Boolean-009/assets/167101531/cb699f1d-9ade-4d83-b933-7d33a087cf5d">

**Comment by vivekkmrpaswan** [comment]
Responsiveness added to section-3 and 4

**Comment by Mayank1st** [comment]
Okay Sorted.
