### ISSUE TITLE
#005:Section-5(Cut your)

### ISSUE THREAD

**Issue by Mayank1st** [Mayank1st/Beas-Boolean-009#6]
@rohit7979 
**Introduction**:
Design Section-5 **Cut your**.

**Steps to Reproduce**:

- [x] Open the website on Chrome browser.
- [x] Navigate to the Header Section.
- [x] Add Responsiveness.
- [x] Add the image.

**Expected Behavior**:
The navbar should align to center when zoom out the webpage.

**Possible Solution**:
Use Bootstrap framework.

**Environment Details**:
- Browser: Chrome 14.0.3
- Operating System: Windows 11.2.3

**Comment by rohit7979** [comment]
Overview:
This pull request addresses an issue where the Add Responsiveness., Add the image are introduced. The fix ensures that the grid aligns correctly across all devices.

 
 
Changes:

Open the website on Chrome browser.
Open the website on Chrome browser.
 Navigate to the Header Section.
 Add Responsiveness.
 Add the image.

Request for Review:
Please review the changes and provide any feedback or suggestions for improvement. Thank you!
References:
Related #5

**Comment by Mayank1st** [comment]
Okay Sorted.
