### ISSUE TITLE
#003:Section-5.1(See why over)

### ISSUE THREAD

**Issue by Mayank1st** [Mayank1st/Beas-Boolean-009#7]
@rohit7979 
**Introduction**:
Design **See why over** Section.

**Steps to Reproduce**:

- [x] Open the website on Chrome browser.
- [x] Navigate to the Header Section.
- [x] Add Responsiveness.
- [x] Add animation using marquee.
- [x] add icon in button.

**Expected Behavior**:
The navbar should align to center when zoom out the webpage.

**Possible Solution**:
Use Bootstrap framework and marquee tag.

**Environment Details**:
- Browser: Chrome 14.0.3
- Operating System: Windows 11.2.3

**Comment by rohit7979** [comment]
Overview:
This pull request addresses an issue where the Add animation using marquee, add icon in button are introduced. The fix ensures that the grid aligns correctly across all devices.

Changes:

Open the website on Chrome browser.
 Navigate to the Header Section.
 Add Responsiveness.
 Add animation using a marquee.
 add icon in button.


Request for Review:
Please review the changes and provide any feedback or suggestions for improvement. Thank you!
References:
Related issue: #6 

![Screenshot 2024-05-12 173310](https://github.com/Mayank1st/Beas-Boolean-009/assets/154664605/e9d873f5-9021-498d-8d8c-b86b3d6e3f52)

**Comment by Mayank1st** [comment]
Okay Done.
