### ISSUE TITLE
 #006:Section-6(The fastest growing)

### ISSUE THREAD

**Issue by Mayank1st** [Mayank1st/Beas-Boolean-009#8]
@amanraj98523 
**Introduction**:
Design **The fastest growing** Section.

**Steps to Reproduce**:

- [x] Open the website on Chrome browser.
- [x] Navigate to the Header Section.
- [x] Add Responsiveness.
- [x] Add marquee.
- [x] add icons.

**Expected Behavior**:
The  **The fastest growing**  should align to center when zoom out the webpage.

**Possible Solution**:
Use Bootstrap framework and fontawesome.

**Environment Details**:
- Browser: Chrome 14.0.3
- Operating System: Windows 11.2.3

**Comment by amanraj98523** [comment]
Overview:
This pull request addresses an issue where the  icons added   on smaller screens, causing a poor user experience. The fix ensures that the icons align correctly across all devices.
Changes:
- Updated CSS styles to adjust the positioning of the login button.
- Added media queries to handle responsiveness on different screen sizes.
Request for Review:
Please review the changes and provide any feedback or suggestions for improvement. Thank you!
References:
Related issue: #8

![day-2](https://github.com/Mayank1st/Beas-Boolean-009/assets/166653226/b9662bdb-dbde-46fc-aa05-28bcb5e5411a)

**Comment by amanraj98523** [comment]
Responsiveness added
