### ISSUE TITLE
#007:Footer Section

### ISSUE THREAD

**Issue by Mayank1st** [Mayank1st/Beas-Boolean-009#9]
@amanraj98523 
**Introduction**:
Design **Footer** Section.

**Steps to Reproduce**:

- [x] Open the website on Chrome browser.
- [x] Navigate to the Header Section.
- [x] Add Responsiveness.
- [x] Use Grid/Flex.
- [x] Add icons or social media links.
- [x] Apply all the anchor tag for proper href redirecting. 

**Expected Behavior**:
The Footer should align to center when zoom out the webpage.

**Possible Solution**:
Use Bootstrap framework..

**Environment Details**:
- Browser: Chrome 14.0.3
- Operating System: Windows 11.2.3

**Comment by amanraj98523** [comment]
Responsiveness added
